---
- name: yum install curl policycoreutils openssh-server nfs-client
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      yum:
        name:
          - curl
          - policycoreutils
          - openssh-server
          - postfix
          - nfs-utils
          - glibc
          - libgcc
          - zlib
          - bzip2
          - libuuid
        state: latest

    - name: openssh-server enabled and running
      service:
        name: sshd
        enabled: true
        state: started
    
    - name: postfix enabled and running
      service:
        name: postfix
        enabled: true
        state: started
        
   #ログイン後手動でpostfixの/etc/postfix/main.cfを編集し[#header_checks = pcre:/etc/postfix/header_checks]をコメントアウトし保存
        #path: /etc/postfix/main.cf
        #regexp: '#header_checks = pcre:/etc/postfix/header_checks'
        #replace: 'header_checks = pcre:/etc/postfix/header_checks'
        
    - name: edit /etc/postfix/header_checks
      lineinfile:
        path: /etc/postfix/header_checks
        line: '/^Received:/ IGNORE'

